bindings for MutableFileSystemSupport
The class **org.eclipse.xtext.xbase.compiler.CompilationTestHelper**
(contained in the bundle _org.eclipse.xtext.xbase.junit_) requires
additional bindings which are created by default when your grammar uses
Xbase.  However, this class could be used also for testing code
generation also in languages that do not use Xbase (this is the case in
the book, Chapter 7, for the examples Entities and Expressions); see
also [this discussion in the Xtext
forum](https://www.eclipse.org/forums/index.php/t/807828/).

The symptom is this exception when running the Junit tests that use
CompilationTestHelper

	com.google.inject.ConfigurationException: Guice configuration errors:
	
	1) No implementation for
org.eclipse.xtend.lib.macro.file.MutableFileSystemSupport was bound.
	  while locating
org.eclipse.xtend.lib.macro.file.MutableFileSystemSupport
	    for field at
org.eclipse.xtext.generator.FileSystemSupportBasedFileSystemAccess.fileSystemSupport(Unknown
Source)
	  while locating
com.google.inject.Provider<org.eclipse.xtext.xbase.compiler.RegisteringFileSystemAccess>
	    for field at
org.eclipse.xtext.xbase.compiler.CompilationTestHelper$Result.fileSystemAccessProvider(Unknown
Source)
	  while locating
com.google.inject.Provider<org.eclipse.xtext.xbase.compiler.CompilationTestHelper$Result>
	    for field at
org.eclipse.xtext.xbase.compiler.CompilationTestHelper.resultProvider(Unknown
Source)
	  while locating org.eclipse.xtext.xbase.compiler.CompilationTestHelper

Change-Id: If7fc66449d2a12f4d0985b31929cecc95cb1e371